
<h1 class="calculator-title">CALCULATOR</h1>
<div  id="calculator" class="calculator">
    <textarea disabled class="showResult" value="" rows="2" cols="20"></textarea>
    <div class="justify-content-around  d-flex  ">
        <div class="numbersCalc ">
            <button value="1" class="btn operationCalculator numberCalc">1</button>
            <button value="2" class="btn operationCalculator numberCalc">2</button>
            <button value="3" class="btn operationCalculator numberCalc">3</button>
            <button value="4" class="btn operationCalculator numberCalc">4</button>
            <button value="5" class="btn operationCalculator numberCalc">5</button>
            <button value="6" class="btn operationCalculator numberCalc">6</button>
            <button value="7" class="btn operationCalculator numberCalc">7</button>
            <button value="8" class="btn operationCalculator numberCalc">8</button>
            <button value="9" class="btn operationCalculator numberCalc">9</button>
            <button value="0" class="btn operationCalculator numberCalc">0</button>
            <button value="" id="clearCalc" class="btn numberCalc">C</button>
            <button value="=" id="evaluate"  class="btn numberCalc">=</button>
        </div>
        <div class="operationsCalc">
            <button value="+" class="btn operation operationCalculator numberCalc">+</button>
            <button value="-" class="btn operation operationCalculator numberCalc">-</button>
            <button value="*" class="btn operation operationCalculator numberCalc">*</button>
            <button value="/" class="btn operation operationCalculator numberCalc">/</button>
        </div>
    </div>

</div>